package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	keydDir   = "/etc/keyd"
	keydConf  = "/etc/keyd/tartarus.conf"
	hwdbConf  = "/etc/udev/hwdb.d/99-tartarus_v2.hwdb"
	stampLine = "# tartarus-profile:"
)

// keydRenames covers the keys keyd spells differently from the kernel. Anything
// not listed is passed through and validated by `keyd check`, which is the real
// authority on key names.
var keydRenames = map[string]string{
	"leftctrl":  "leftcontrol",
	"rightctrl": "rightcontrol",
}

// The device id written into [ids].
//
// A bare vendor:product is the default because every keyd version accepts it.
// The keypad exposes several interfaces under that one id — two keyboard
// interfaces, only one of which emits its keys, plus a mouse interface carrying
// the scroll wheel. A profile can narrow that when its keyd supports the
// syntax, by setting `device` to something else:
//
//	k:1532:022b            keyboards only
//	1532:022b:fab63040     one specific interface, keyd 2.5 and later
//
// Whatever the profile names is passed through unchanged; `keyd monitor` prints
// the three-part ids for the machine it runs on.

func keydName(value string) string {
	if renamed, ok := keydRenames[strings.ToLower(value)]; ok {
		return renamed
	}
	return value
}

// RenderKeyd compiles a profile into a keyd config.
//
// Every input the profile does not bind is set to noop, so a stray press cannot
// type into the game. That was the intent behind the `=0` lines in the original
// .map files, which bound the digit zero instead.
func RenderKeyd(p *Profile) (string, error) {
	targets := make([]struct{ Stock, Target, Label string }, 0, len(layout))
	for _, in := range layout {
		value, bound := p.Bindings[in.Label]
		target := "noop"
		switch {
		case !bound && p.Passthrough:
			continue
		case !bound:
			// unbound is the default
		default:
			resolved, err := p.Resolve(in.Label, value)
			if err != nil {
				return "", err
			}
			if !isOff(resolved) {
				target = keydName(resolved)
			}
		}
		targets = append(targets, struct{ Stock, Target, Label string }{in.Stock, target, in.Label})
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s %s\n", stampLine, p.Slug)
	fmt.Fprintf(&b, "# %s\n", p.Name)
	b.WriteString("# Generated by tartarus (keyd backend). Edit the profile, not this file.\n")
	b.WriteString("#\n")
	b.WriteString("# The left-hand side is the key the keypad sends before remapping:\n")
	b.WriteString("#   k01=1  k02=2  k03=3  k04=4  k05=5\n")
	b.WriteString("#   k06=tab  k07=q  k08=w  k09=e  k10=r\n")
	b.WriteString("#   k11=capslock  k12=a  k13=s  k14=d  k15=f\n")
	b.WriteString("#   k16=leftshift  k17=z  k18=x  k19=c\n")
	b.WriteString("#   thumb=leftalt  pad=up/down/left/right  bar=space\n")
	b.WriteString("\n[ids]\n")
	fmt.Fprintf(&b, "%s\n\n", p.Device)
	b.WriteString("[main]\n")
	// No trailing comments: not every keyd version strips them from a value,
	// and a version that does not would read `esc  # k01` as the key name.
	for _, t := range targets {
		fmt.Fprintf(&b, "%s = %s\n", t.Stock, t.Target)
	}
	return b.String(), nil
}

// ActiveProfile reads back the slug stamped into the installed config.
func ActiveProfile() string {
	data, err := os.ReadFile(keydConf)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, stampLine) {
			return strings.TrimSpace(strings.TrimPrefix(line, stampLine))
		}
	}
	return "unknown"
}

// conflictingConfigs finds other keyd configs that also claim our device.
// keyd allows a device id in only one config file, so a stale config silently
// wins or loses depending on load order.
func conflictingConfigs(device string) []string {
	entries, err := os.ReadDir(keydDir)
	if err != nil {
		return nil
	}
	var clashes []string
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".conf") {
			continue
		}
		path := filepath.Join(keydDir, entry.Name())
		if path == keydConf {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if strings.Contains(string(data), device) {
			clashes = append(clashes, path)
		}
	}
	return clashes
}

// Apply installs the config and reloads keyd, restoring the previous config if
// keyd rejects the new one.
func Apply(p *Profile, dryRun bool) error {
	content, err := RenderKeyd(p)
	if err != nil {
		return err
	}

	if keydBinary == "" {
		if !dryRun {
			return fmt.Errorf(
				"cannot find the keyd binary. It is not on PATH, systemd does not " +
					"report a keyd.service, and it is not in the usual places. Set " +
					"TARTARUS_KEYD=/path/to/keyd if it lives somewhere else")
		}
		fmt.Fprintln(os.Stderr, "note: keyd not found (dry run, continuing)")
	}
	if _, err := os.Stat(hwdbConf); err == nil {
		fmt.Fprintf(os.Stderr,
			"warning: %s is still installed. It remaps the keypad in the kernel before\n"+
				"         keyd sees it, and keyd matches on what the device sends, so a\n"+
				"         profile keyed on the stock names will not match. Remove it, run\n"+
				"         `systemd-hwdb update`, then unplug and replug the keypad:\n"+
				"         deleting the file does not reset the keycode table already\n"+
				"         written to the device.\n", hwdbConf)
	}
	for _, clash := range conflictingConfigs(p.Device) {
		fmt.Fprintf(os.Stderr, "warning: %s also claims %s; keyd allows a device in only one config\n",
			clash, p.Device)
	}

	if dryRun {
		fmt.Printf("would write %s:\n\n%s\n", keydConf, content)
		fmt.Println("would run: keyd check " + keydConf)
		fmt.Println("would run: keyd reload")
		return nil
	}

	previous, readErr := os.ReadFile(keydConf)
	if err := os.MkdirAll(keydDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(keydConf, []byte(content), 0o644); err != nil {
		return err
	}

	restore := func() {
		if readErr == nil {
			_ = os.WriteFile(keydConf, previous, 0o644)
		} else {
			_ = os.Remove(keydConf)
		}
		_ = keyd("reload").Run()
	}

	if keydSupportsCheck() {
		if out, err := keyd("check", keydConf).CombinedOutput(); err != nil {
			restore()
			return fmt.Errorf("keyd rejected the config (previous one restored):\n%s", strings.TrimSpace(string(out)))
		}
	} else {
		fmt.Fprintln(os.Stderr,
			"note: this keyd has no `check` subcommand, so the config is not validated "+
				"before loading; a failed reload still restores the previous one")
	}
	if out, err := keyd("reload").CombinedOutput(); err != nil {
		restore()
		return fmt.Errorf("keyd reload failed (previous config restored):\n%s", strings.TrimSpace(string(out)))
	}
	return nil
}

// keydSupportsCheck reports whether this keyd offers the `check` subcommand.
// Config linting was added part-way through keyd's history, and older releases
// are still in use, so its absence must not look like a broken config.
func keydSupportsCheck() bool {
	out, _ := keyd("--help").CombinedOutput()
	return strings.Contains(string(out), "check")
}

// Off removes the mapping and reloads keyd, leaving the keypad at stock.
func Off(dryRun bool) error {
	if _, err := os.Stat(keydConf); err != nil {
		fmt.Println("no mapping installed; nothing to do")
		return nil
	}
	if dryRun {
		fmt.Printf("would remove %s\nwould run: keyd reload\n", keydConf)
		return nil
	}
	if err := os.Remove(keydConf); err != nil {
		return err
	}
	if keydBinary != "" {
		if out, err := keyd("reload").CombinedOutput(); err != nil {
			return fmt.Errorf("keyd reload failed:\n%s", strings.TrimSpace(string(out)))
		}
	}
	fmt.Println("mapping removed; the keypad is back to its stock layout")
	return nil
}

// Elevate re-runs this binary under sudo. It is called only after the profile
// has compiled, so a mistake never costs a password prompt.
func Elevate(args []string) error {
	if os.Geteuid() == 0 {
		return nil
	}
	sudo, err := exec.LookPath("sudo")
	if err != nil {
		return fmt.Errorf("this needs root and sudo is not available")
	}
	self, err := os.Executable()
	if err != nil {
		return err
	}
	cmd := exec.Command(sudo, append([]string{self}, args...)...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return err
	}
	os.Exit(0)
	return nil
}
